import { Editor } from '@tiptap/core';
import StarterKit from '@tiptap/starter-kit';
import Image from '@tiptap/extension-image';
import { mountCover } from './cover.js';

const $ = id => document.getElementById(id);
const error = message => { $('error').textContent = message; };
const templates = {
 daily: ['日常图文', ['今天记录什么','一个值得留下的细节','我的感受']],
 tutorial: ['步骤教程', ['这篇能帮你解决什么','开始前的准备','第一步','第二步','结果与注意事项']],
 review: ['体验测评', ['为什么尝试它','我的使用场景','喜欢的地方','不够好的地方','适合谁']],
 pitfall: ['踩坑记录', ['遇到了什么问题','尝试过的方法','最后如何解决','下次怎样避免']],
};
document.querySelector('.compose').inert = true;
let ready = false, dirty = false, timer, savedAt = '', cover, changeVersion = 0;
const editor = new Editor({element:$('editor'),extensions:[StarterKit,Image.configure({allowBase64:true})],content:'<p>从这里开始写，或选择上方的内容模板。</p>',editorProps:{attributes:{'aria-label':'文章正文','role':'textbox','aria-multiline':'true'}},onUpdate(){changed();}});
const db = new Promise((resolve,reject)=>{const r=indexedDB.open('x-studio-v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('drafts');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
async function readDraft(){const d=await db;return new Promise((res,rej)=>{const r=d.transaction('drafts').objectStore('drafts').get('current');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
function snapshot(){return {version:1,title:$('post-title').value,summary:$('post-summary').value,content:editor.getJSON(),layout:$('article-layout').value,cover:cover?.getState(),savedAt:new Date().toISOString()};}
let queue=Promise.resolve();
function save(){if(!ready)return;const value=snapshot(), version=changeVersion;queue=queue.catch(()=>{}).then(async()=>{const d=await db;await new Promise((res,rej)=>{const t=d.transaction('drafts','readwrite');t.objectStore('drafts').put(value,'current');t.oncomplete=res;t.onerror=()=>rej(t.error);t.onabort=()=>rej(t.error);});savedAt=value.savedAt;if(version===changeVersion){dirty=false;$('save-state').textContent='已保存到本机 '+new Date(savedAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});}}).catch(()=>{$('save-state').textContent='保存失败，请备份草稿';error('浏览器存储不可用或已满，请点击“备份草稿”保留内容。');});}
function renderPreview(){ $('preview-title').textContent=$('post-title').value||'你的下一篇故事';$('preview-summary').textContent=$('post-summary').value;$('preview-body').innerHTML=editor.getHTML();$('article-preview').className=$('article-layout').value;$('word-count').textContent=editor.getText().replace(/\s/g,'').length+' 字';}
function changed(){renderPreview();if(!ready)return;dirty=true;changeVersion+=1;$('save-state').textContent='正在保存到本机…';clearTimeout(timer);timer=setTimeout(save,350);}
cover=mountCover($('cover-editor'),{onChange:changed});
function restore(value){if(value?.version!==1||value.content?.type!=='doc'||typeof value.title!=='string'||typeof value.summary!=='string')throw Error('不是有效的创作室草稿');if(value.cover?.image&&!/^data:image\/(png|jpeg|webp);base64,/.test(value.cover.image))throw Error('封面图片格式无效');$('post-title').value=value.title.slice(0,160);$('post-summary').value=value.summary;editor.commands.setContent(value.content);$('article-layout').value=['plain','editorial','notes'].includes(value.layout)?value.layout:'plain';if(value.cover)cover.setState(value.cover);renderPreview();}
(async()=>{try{const v=await readDraft();if(v)restore(v);$('save-state').textContent=v?'已恢复本机草稿':'本机草稿 · 尚未同步';}catch{error('无法读取本机草稿，可以继续编辑并导出备份。');$('save-state').textContent='本机存储不可用';}finally{ready=true;document.querySelector('.compose').inert=false;renderPreview();}})();
['post-title','post-summary','article-layout'].forEach(id=>$(id).addEventListener('input',changed));
document.querySelectorAll('[data-template]').forEach(button=>button.addEventListener('click',()=>{if(!ready)return;const initial='从这里开始写，或选择上方的内容模板。';if(editor.getText().trim()&&editor.getText().trim()!==initial&&!confirm('套用内容模板会替换正文。标题和封面保留，正文可通过“撤销”恢复。继续吗？'))return;const key=button.dataset.template;editor.commands.setContent({type:'doc',content:templates[key][1].flatMap(text=>[{type:'heading',attrs:{level:2},content:[{type:'text',text}]},{type:'paragraph'}])});document.querySelectorAll('[data-template]').forEach(b=>b.classList.toggle('active',b===button));changed();}));
document.querySelectorAll('[data-command]').forEach(button=>{button.addEventListener('mousedown',e=>e.preventDefault());button.addEventListener('click',()=>{const c=editor.chain().focus();({bold:()=>c.toggleBold(),heading:()=>c.toggleHeading({level:2}),bullet:()=>c.toggleBulletList(),quote:()=>c.toggleBlockquote(),undo:()=>c.undo()})[button.dataset.command]().run();});});
async function compress(file){if(!file.type.startsWith('image/'))throw Error('请选择图片文件');if(file.size>30*1024*1024)throw Error('单张图片请小于 30 MB');const url=URL.createObjectURL(file);try{const img=await new Promise((res,rej)=>{const i=new window.Image();i.onload=()=>res(i);i.onerror=()=>rej(Error('无法读取这张图片，请换成 JPEG、PNG 或 WebP'));i.src=url;});const scale=Math.min(1,1600/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.85);}finally{URL.revokeObjectURL(url);}}
$('body-images').addEventListener('change',async e=>{const files=Array.from(e.target.files||[]);if(files.length>12){error('一次最多插入 12 张照片');e.target.value='';return;}for(let i=0;i<files.length;i++){try{$('image-status').textContent=`正在处理照片 ${i+1}/${files.length}`;const src=await compress(files[i]);editor.chain().focus().setImage({src,alt:files[i].name}).insertContent({type:'paragraph'}).run();}catch(err){error(err.message);}}$('image-status').textContent='照片处理完成，可选中照片后删除或继续插入。';e.target.value='';});
function download(data,name,type){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('download-draft').addEventListener('click',()=>download(JSON.stringify(snapshot()),'创作室草稿.json','application/json'));
$('restore-draft').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>40*1024*1024)throw Error('备份文件过大');const v=JSON.parse(await file.text());if(!confirm('用备份替换当前草稿？建议先备份当前内容。'))return;restore(v);changed();error('');}catch(err){error('恢复失败：'+err.message);}finally{e.target.value='';}});
$('preview-toggle').addEventListener('click',()=>{const active=document.body.classList.toggle('focus-preview');$('preview-toggle').textContent=active?'返回编辑':'预览文章';renderPreview();const canvas=$('cover-editor').querySelector('canvas');if(canvas){$('preview-cover').src=canvas.toDataURL('image/png');$('preview-cover').hidden=false;}if(active)save();window.scrollTo({top:0});});
const escapeHtml=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('download-html').addEventListener('click',()=>{const canvas=$('cover-editor').querySelector('canvas');download(`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml($('post-title').value||'文章')}</title><style>body{max-width:720px;margin:40px auto;padding:20px;font:18px/1.9 system-ui;color:#262821}img{max-width:100%;height:auto}blockquote{border-left:3px solid #999;padding-left:20px}</style>${canvas?'<img alt="封面" src="'+canvas.toDataURL('image/png')+'">':''}<h1>${escapeHtml($('post-title').value)}</h1><p>${escapeHtml($('post-summary').value)}</p>${editor.getHTML()}</html>`,'文章.html','text/html');});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&dirty)save();});

document.querySelectorAll('[data-photo]').forEach(button=>{button.addEventListener('mousedown',e=>e.preventDefault());button.addEventListener('click',()=>{const {state}=editor;const {from,to,node}=state.selection;if(node?.type.name!=='image'){ $('image-status').textContent='请先点击正文中的照片，再移动或删除。';return;}if(button.dataset.photo==='delete'){editor.chain().focus().deleteSelection().run();return;}const blocks=[];state.doc.forEach((n,pos)=>blocks.push({node:n,pos}));const index=blocks.findIndex(b=>b.pos===from);const target=button.dataset.photo==='up'?blocks[index-1]:blocks[index+1];if(!target){$('image-status').textContent='照片已经在边缘。';return;}const pos=button.dataset.photo==='up'?target.pos:target.pos+target.node.nodeSize-node.nodeSize;editor.view.dispatch(state.tr.delete(from,to).insert(pos,node));editor.commands.setNodeSelection(pos);$('image-status').textContent='已调整照片顺序。';});});
